FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY ../sources/springboot.reactive/target/springboot.reactive-1.0.jar /app/springboot.reactive-1.0.jar

CMD ["java", "-jar", "/app/springboot.reactive-1.0.jar"]
