FROM ghcr.io/graalvm/jdk-community:21

WORKDIR /app
COPY ../sources/springboot.imperative/target/springboot.imperative-1.0.jar /app/springboot.imperative-1.0.jar

CMD ["java", "-jar", "/app/springboot.imperative-1.0.jar"]
