apiVersion: v1
kind: Service
metadata:
  name: quarkus-imperative-redhat-service
spec:
  selector:
    app: quarkus-imperative-redhat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort