FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest

WORKDIR /app
COPY ../sources/springboot.imperative/target/springboot.imperative-1.0.jar /app/springboot.imperative-1.0.jar

CMD ["java", "-jar", "/app/springboot.imperative-1.0.jar"]
