FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest

WORKDIR /app
COPY ../sources/quarkus.imperative/target/quarkus-app/lib/ /app/lib/
COPY ../sources/quarkus.imperative/target/quarkus-app/app/ /app/app/
COPY ../sources/quarkus.imperative/target/quarkus-app/quarkus/ /app/quarkus/
COPY ../sources/quarkus.imperative/target/quarkus-app/quarkus-run.jar /app/quarkus-run.jar

CMD ["java", "-jar", "/app/quarkus-run.jar"]