FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest

WORKDIR /app
COPY ../sources/springboot.reactive/target/springboot.reactive-1.0.jar /app/springboot.reactive-1.0.jar

CMD ["java", "-jar", "/app/springboot.reactive-1.0.jar"]
