FROM ubi9/openjdk-21:latest

WORKDIR /app
COPY ./source/target/metrics-jvm-redhat-1.0.0.jar /app/metrics-jvm-redhat-1.0.0.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/metrics-jvm-redhat-1.0.0.jar"]
